"""create vocabularies and vocabulary items

Revision ID: 23b512857f1c
Revises: f73af88ef924
Create Date: 2026-07-21 16:38:36.875803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23b512857f1c'
down_revision: Union[str, Sequence[str], None] = 'f73af88ef924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabularies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('word', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('normalized_word', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocabularies_deck_id_is_deleted_created_at', 'vocabularies', ['deck_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index('uq_vocabularies_deck_id_normalized_word_active', 'vocabularies', ['deck_id', 'normalized_word'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('vocabulary_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('part_of_speech', sa.Enum('noun', 'verb', 'adjective', 'adverb', 'pronoun', 'preposition', 'conjunction', 'determiner', 'interjection', 'numeral', 'auxiliary', 'modal', 'particle', 'phrase', 'idiom', 'other', name='part_of_speech'), nullable=False),
    sa.Column('ipa', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('english_meaning', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('vietnamese_meaning', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('grammar_note', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level'), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 1', name='ck_vocab_items_position_positive'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocab_items_vocabulary_id_deleted_position', 'vocabulary_items', ['vocabulary_id', 'is_deleted', 'position'], unique=False)
    op.create_index('uq_vocab_items_vocabulary_id_position_active', 'vocabulary_items', ['vocabulary_id', 'position'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_vocab_items_vocabulary_id_position_active', table_name='vocabulary_items', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_vocab_items_vocabulary_id_deleted_position', table_name='vocabulary_items')
    op.drop_table('vocabulary_items')
    op.drop_index('uq_vocabularies_deck_id_normalized_word_active', table_name='vocabularies', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_vocabularies_deck_id_is_deleted_created_at', table_name='vocabularies')
    op.drop_table('vocabularies')
    sa.Enum(name='cefr_level').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='part_of_speech').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
