"""add user identities

Revision ID: 6f9505bee599
Revises: 9ed6e2955071
Create Date: 2026-07-29 15:20:46.063970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f9505bee599'
down_revision: Union[str, Sequence[str], None] = '9ed6e2955071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('provider_email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_user_identities_provider_subject'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_identities_user_provider')
    )
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("user_identities")

    fallback_password_hash = (
        "$argon2id$v=19$m=65536,t=3,p=4$"
        "W/gItM2vlfrxvIZibB3MLQ$"
        "woHM9QYtRbqy9Iy6xe+LQDU4oi0z5Ztvqj/vQcwaIKk"
    )

    op.execute(
        sa.text(
            """
            UPDATE users
            SET hashed_password = :fallback_password_hash
            WHERE hashed_password IS NULL
            """
        ).bindparams(
            fallback_password_hash=fallback_password_hash,
        )
    )

    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
