"""create collocation and example sentence

Revision ID: 9ed6e2955071
Revises: 23b512857f1c
Create Date: 2026-07-28 11:09:24.975882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ed6e2955071'
down_revision: Union[str, Sequence[str], None] = '23b512857f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_item_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('normalized_phrase', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('english_meaning', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('vietnamese_meaning', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_item_id'], ['vocabulary_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collocations_vocabulary_item_id_is_deleted_position', 'collocations', ['vocabulary_item_id', 'is_deleted', 'position'], unique=False)
    op.create_index('uq_collocations_vocabulary_item_id_normalized_phrase_active', 'collocations', ['vocabulary_item_id', 'normalized_phrase'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('example_sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_item_id', sa.Integer(), nullable=False),
    sa.Column('collocation_id', sa.Integer(), nullable=True),
    sa.Column('sentence', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('normalized_sentence', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('vietnamese_meaning', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collocation_id'], ['collocations.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_item_id'], ['vocabulary_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_example_sentences_collocation_id_is_deleted_position', 'example_sentences', ['collocation_id', 'is_deleted', 'position'], unique=False)
    op.create_index('ix_example_sentences_vocabulary_item_id_is_deleted_position', 'example_sentences', ['vocabulary_item_id', 'is_deleted', 'position'], unique=False)
    op.create_index('uq_examples_item_normalized_sentence_active', 'example_sentences', ['vocabulary_item_id', 'normalized_sentence'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_examples_item_normalized_sentence_active', table_name='example_sentences', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_example_sentences_vocabulary_item_id_is_deleted_position', table_name='example_sentences')
    op.drop_index('ix_example_sentences_collocation_id_is_deleted_position', table_name='example_sentences')
    op.drop_table('example_sentences')
    op.drop_index('uq_collocations_vocabulary_item_id_normalized_phrase_active', table_name='collocations', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_collocations_vocabulary_item_id_is_deleted_position', table_name='collocations')
    op.drop_table('collocations')
    # ### end Alembic commands ###
