"""create decks table

Revision ID: bcbdd0bd3f0b
Revises: 21f9910e5cfc
Create Date: 2026-07-17 16:49:22.406802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bcbdd0bd3f0b'
down_revision: Union[str, Sequence[str], None] = '21f9910e5cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decks_is_public_is_deleted_created_at', 'decks', ['is_public', 'is_deleted', 'created_at'], unique=False)
    op.create_index('ix_decks_user_id_is_deleted_created_at', 'decks', ['user_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index('uq_decks_user_id_normalized_name_active', 'decks', ['user_id', 'normalized_name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_decks_user_id_normalized_name_active', table_name='decks', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_decks_user_id_is_deleted_created_at', table_name='decks')
    op.drop_index('ix_decks_is_public_is_deleted_created_at', table_name='decks')
    op.drop_table('decks')
    # ### end Alembic commands ###
